### ISSUE TITLE
Random Card Picker

### ISSUE THREAD

**Issue by fgubler** [JordanPawlett/cards-against-formality-services#24]
It often happens that black or white cards appear multiple times within the same game.
That is a bit annoying. Therefore, it would be great, if the card-picker considered only cards not yet played in this game.

But anyway: great work and thanks a lot :-)

**Comment by JordanPawlett** [comment]
Thank you. Definitely a bug, the card selection is not intended to be random. I'll try find some time to get a fix in!

**Comment by JordanPawlett** [comment]
Thanks you again for reporting this bug. This issue is hopefully resolved now. Let me know if you see it occur agian.

I have just released a new version, with a few bug fixes and features. Do not hesitate to bring any bugs to my attention.
https://github.com/JordanPawlett/cards-against-formality-services/releases/tag/v0.0.8
